name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  sonar-check:
    name: Sonar Check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: SonarScanner Begin
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH
          dotnet sonarscanner begin `
            /k:"Niket-crypto_SdrProject" `
            /o:"niket-crypto" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.cs.opencover.reportsPaths="**/coverage.xml" `
            /d:sonar.coverage.exclusions="**/*.cs" `
            /d:sonar.exclusions="**/bin/**,**/obj/**,**/sonarcloud.yml" `
            /d:sonar.qualitygate.wait=true
        shell: pwsh

      - name: Restore
        run: dotnet restore SdrSolution.sln

      - name: Build
        run: dotnet build SdrSolution.sln -c Release --no-restore

      - name: Tests with coverage
        run: |
          dotnet test SdrSolution.sln -c Release --no-build `
            /p:CollectCoverage=true `
            /p:CoverletOutputFormat=opencover `
            /p:CoverletOutput="../../TestResults/coverage.xml"
        shell: pwsh

      - name: SonarScanner End
        run: |
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        shell: pwsh

